In [5]:
import numpy as np

In [31]:
n = 3
Q = 3

# A = np.array([
#     [0, 1, 2, 3],
#     [0, 0, 1, 2],
#     [0, 2, 2, 3]
# ])

A = np.array([
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 1, 0]
])

In [32]:
class ResourceAllocationSolver:
    
    def solve(self, revenue_matrix, resources_count, agents_count):
        n, m = len(revenue_matrix), len(revenue_matrix[0])
        opt_matrix = np.zeros((n, m))
        X = np.zeros((n, m))
        
        for index, item in enumerate(revenue_matrix[0]):
            opt_matrix[0][index] = item
            X[0][index] = item
        
        current_agent = 1
        
        while current_agent < agents_count:
            for q in range(resources_count + 1):
                combinations = self.get_combinations(q)
                potential_revenues_list = []
                
                for tup in combinations:
                    first_index, second_index = tup
            
                    potential_revenues_list.append(opt_matrix[current_agent - 1][first_index] + \
                                                   revenue_matrix[current_agent][second_index])
                
                
                max_value = max(potential_revenues_list)
                opt_matrix[current_agent][q] = max_value
                max_value_index = potential_revenues_list.index(max_value)
                
                X[current_agent][q] = combinations[max_value_index][1]
                
            
            current_agent += 1
        
        solution = np.zeros(n)
        resources_left = resources_count
        
        for k in reversed(range(agents_count)):
            m = int(resources_left)
            current = X[k][m]
            solution[k] = current
            resources_left -= current
        
        if resources_left > 0 and solution[0] == 0:
            solution[0] = resources_left
        
        return solution, opt_matrix, X
        
    @staticmethod
    def get_combinations(num):
        combinations = []
        for item in reversed(range(num + 1)):
            combinations.append((item, num - item))
        
        return combinations

In [33]:
solver = ResourceAllocationSolver()
solution, OPT, X = solver.solve(A, Q, n)

print(f'Solution:\n{solution}\n')
print(f'OPT matrix:\n{OPT}\n')
print(f'Max revenue:\n{np.max(OPT)}\n')
print(f'X matrix:\n{X}\n')

Solution:
[1. 0. 2.]

OPT matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 1.]]

Max revenue:
1.0

X matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 2. 2.]]

